using System;
using System.Collections.Generic;

namespace VcxProjLib
{
    class VCXProjectConfiguration
    {
        public String Configuration { get; private set; }
        public String Platform { get; private set; }

        /* configuration-dependent */
        /* 1. Configuration section */
        public Boolean UseDebugLibraries = true;
        public String ConfigurationType = "Makefile";
        public String RemoteBuildDir = "/local/store/git/realtek_iss";

        /* 2. Outside of section */
        public String BuildCommandLine = "echo Project generated by VCXProjWriter; build";
        public String ReBuildCommandLine = "echo Project generated by VCXProjWriter; rebuild";
        public String CleanCommandLine = "echo Project generated by VCXProjWriter; clean";
        public String RemoteBuildCommandLine = @"source /local/store/rtl_sdk.sh &amp;&amp; ./mybuild.sh --wm";
        public String RemoteCleanCommandLine = @"source /local/store/rtl_sdk.sh &amp;&amp; ./mybuild.sh -C";
        public String RemoteReBuildCommandLine = @"$(RemoteCleanCommandLine) &amp;&amp; $(RemoteBuildCommandLine)";
        public String RemoteProjectDir = "/local/store/git/realtek_iss";
        public Boolean LocalRemoteCopySources = true;
        /* IntelliSense config */
        public List<String> NMakeIncludeSearchPath;
        public List<KeyValuePair<String, ValueType>> NMakePreprocessorDefinitions;
        public List<String> NMakeForcedIncludes;
        public String AdditionalOptions = "";
    }
}
